### ISSUE TITLE
Question about small value padding

### ISSUE THREAD

**Issue by bdh0404** [OpenMPDK/KVSSD#5]
In "KV SSD Firmware Introduction" file of the KV SSD Presentation wiki, the KV-SSD features value size of 0B~2MB with padded up to 1KB for small values internally. I have an idea for using KV-SSD for my research. However, I use key-value storage that all values are size of 4 or 8 bytes, which is very small compared to 1KB. In that case, there could be a lot of useless space by padding. I'd like to know weather there is a way not to pad for storing lots of small values in KV-SSD.

**Comment by kvssd-support** [comment]
We need to limit the total number of keys by adding padding for small values due to the limitation of resources in KV SSD as well as to maintain a sustainable write performance level.

We also have a plan to gradually reduce the padding size in the near future but the minimal padding size will not be less than a hundred bytes.
